### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by ileenamitra** [gymreklab/TRTools#107]
Can't build dockerfile b/c of error when loading dependencies for trtools
RuntimeError: Scikit-learn requires Python 3.6 or later. The current Python version is 3.5.2 installed in /usr/bin/python3.

**Comment by gymreklab** [comment]
@LiterallyUniqueLogin can we remove this dependency? As far as I can tell it's not used anymore. It is imported into `qcSTR.py` but not used.

**Comment by LiterallyUniqueLogin** [comment]
I would like to keep it, if that's okay. I may use it in the future, and I've already done the setup work to get it here.

I'm pretty sure this issue comes up because we try to install trtools from source (which is highly not recommended, we should either install via pip or simply download the repo and use it directly). Can I just change this to install trtools via pip or was there a reason for this other than this Dockerfile was created before trtools was installable via pip?

**Comment by LiterallyUniqueLogin** [comment]
This is the fix I'm suggesting, feel free to suggest a different one, but this works: https://github.com/gymreklab/TRTools/pull/108

**Comment by gymreklab** [comment]
I prefer #111. Newer ubuntu (20.04) uses Python3.8. We use the Docker in our AWS workflows and may need to occasionally access different branches still in development. It is more desireable for us to have the github version installed. Unless there are any objections I'd like to merge #111.

**Comment by LiterallyUniqueLogin** [comment]
Always happy to upgrade. Didn't realize that was in the cards. Good to know r.e. AWS.
