### ISSUE TITLE
mergeSTR does not output `GRID` info

### ISSUE THREAD

**Issue by microtan0902** [gymreklab/TRTools#148]
Dear authors,

I am using mergeSTR to merge VCFs from a trio, and use MonSTR to identify denovo STRs. however, MonSTR reports an error as below:

```
[MonSTR-2.0] ProgressMeter: Running de novo analysis...
[MonSTR-2.0] ProgressMeter: Opening priors file...
[MonSTR-2.0] ERROR: Required INFO field GRID not present in VCF
```

I checked the merged VCF. There is no `GRID` included in the merged VCF. but it does include in the individual VCFs. I guess this is a bug or something I missed during the merging step. Please help me to figure it out. Thanks!

`mergeSTR --vcfs ${FILE1},${FILE2},${FILE3} --out ~/test --vcftype gangstr`

mergeSTR --version 4.0.1

**Comment by gymreklab** [comment]
Unfortunately the GRID file does not currently get merged. This is because the GRID (and FORMAT/GGL) fields can cover a different range of possible alleles in the files being merged. There is not an obvious way to merge them so we don't have any immediate plans to support it.

If you'd like to use GangSTR files as input to MonSTR, we recommend running GangSTR jointly on all samples in the same family at once, and outputting the `--include-ggl` field to output all of the genotype likelihoods. That way the likelihoods will be comparable across all family members.
